apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: test-vpa-gitops
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: hello-openshift
  updatePolicy:
    updateMode: "Off"